unit uCadClientes2;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, uPai, ExtCtrls, StdCtrls, Mask, DBCtrls, DB, Menus, XPMenu,
  Buttons, MMJPanel, FMTBcd, JvExMask, JvToolEdit, JvBaseEdits,
  JvDBControls, DBClient, Provider, SqlExpr;

type
  TfCadClientes2 = class(TfPai)
    grp1: TGroupBox;
    lblCnpj: TLabel;
    lblIE: TLabel;
    lblOrgaoEmissor: TLabel;
    dbedtCNPJ: TDBEdit;
    dbedtINSCESTADUAL: TDBEdit;
    dbedtRG: TDBEdit;
    grp2: TGroupBox;
    lbl2: TLabel;
    dbedtDATANASC: TDBEdit;
    sds_cli: TSQLDataSet;
    sds_cliCODICLIENTE: TIntegerField;
    sds_cliNOMECLIENTE: TStringField;
    sds_cliRAZAOSOCIAL: TStringField;
    sds_cliCONTATO: TStringField;
    sds_cliTIPOFIRMA: TSmallintField;
    sds_cliCPF: TStringField;
    sds_cliCNPJ: TStringField;
    sds_cliINSCESTADUAL: TStringField;
    sds_cliRG: TStringField;
    sds_cliSEGMENTO: TSmallintField;
    sds_cliREGIAO: TSmallintField;
    sds_cliLIMITECREDITO: TFloatField;
    sds_cliDATACADASTRO: TDateField;
    sds_cliCODUSUARIO: TIntegerField;
    sds_cliSTATUS: TSmallintField;
    sds_cliHOMEPAGE: TStringField;
    sds_cliPRAZORECEBIMENTO: TSmallintField;
    sds_cliPRAZOENTREGA: TSmallintField;
    sds_cliCODBANCO: TSmallintField;
    sds_cliBASE_ICMS: TSmallintField;
    sds_cliDATANASC: TDateField;
    sds_cliCONTA_CLIENTE: TStringField;
    sds_cliOBS: TStringField;
    sds_cliBANCO: TStringField;
    sds_cliNOMEUSUARIO: TStringField;
    sds_cliTEM_IE: TStringField;
    sds_cliDATARESC: TDateField;
    sds_cliNOMEMAE: TStringField;
    sds_cliSEXO: TStringField;
    sds_cliFORMA_CORRESPOND: TStringField;
    sds_cliGRUPO_CLIENTE: TStringField;
    sds_cliCODINCLUCANC: TIntegerField;
    sds_cliEXIST_COBERT: TStringField;
    sds_cliEXISTCOPART: TStringField;
    sds_cliDATAREINC: TDateField;
    sds_cliGERAAVISO: TStringField;
    sds_cliGERAENV: TStringField;
    sds_cliGERABOL: TStringField;
    sds_cliEMVIAGEM: TStringField;
    sds_cliDTAALTERA: TDateField;
    sds_cliSERIELETRA: TStringField;
    sds_cliSERIE: TStringField;
    sds_cliRA: TStringField;
    sds_cliCURSO: TStringField;
    sds_cliIP: TStringField;
    sds_cliN_CONTRATO: TStringField;
    sds_cliMAC: TStringField;
    sds_cliMARCA: TStringField;
    sds_cliBANDA_UPLOAD: TStringField;
    sds_cliBANDA_DOWLOAD: TStringField;
    sds_cliTORRE_CONECCAO: TStringField;
    sds_cliCOD_FAIXA: TIntegerField;
    sds_cliDESCONTO: TFloatField;
    sds_cliMENSALIDADE: TFloatField;
    sds_cliPAI: TStringField;
    sds_cliLOCALTRABALUNO: TStringField;
    sds_cliDIVERSO1: TStringField;
    sds_cliDIVERSO2: TStringField;
    sds_cliTELTRABALUNO: TStringField;
    sds_cliDATA_MATRICULA: TSQLTimeStampField;
    sds_cliSITUACAOESCOLAR: TStringField;
    sds_cliCOD_TRANPORTADORA: TIntegerField;
    sds_cliCODRESPONSAVEL: TIntegerField;
    sds_cliCFOP: TStringField;
    dsp_cli: TDataSetProvider;
    cds_cli: TClientDataSet;
    cds_cliCODCLIENTE: TIntegerField;
    cds_cliNOMECLIENTE: TStringField;
    cds_cliRAZAOSOCIAL: TStringField;
    cds_cliCONTATO: TStringField;
    cds_cliTIPOFIRMA: TSmallintField;
    cds_cliCPF: TStringField;
    cds_cliCNPJ: TStringField;
    cds_cliINSCESTADUAL: TStringField;
    cds_cliRG: TStringField;
    cds_cliSEGMENTO: TSmallintField;
    cds_cliREGIAO: TSmallintField;
    cds_cliLIMITECREDITO: TFloatField;
    cds_cliDATACADASTRO: TDateField;
    cds_cliCODUSUARIO: TIntegerField;
    cds_cliSTATUS: TSmallintField;
    cds_cliHOMEPAGE: TStringField;
    cds_cliPRAZORECEBIMENTO: TSmallintField;
    cds_cliPRAZOENTREGA: TSmallintField;
    cds_cliCODBANCO: TSmallintField;
    cds_cliBASE_ICMS: TSmallintField;
    cds_cliDATANASC: TDateField;
    cds_cliCONTA_CLIENTE: TStringField;
    cds_cliOBS: TStringField;
    cds_cliBANCO: TStringField;
    cds_cliNOMEUSUARIO: TStringField;
    cds_cliTEM_IE: TStringField;
    cds_cliDATARESC: TDateField;
    cds_cliNOMEMAE: TStringField;
    cds_cliSEXO: TStringField;
    cds_cliFORMA_CORRESPOND: TStringField;
    cds_cliGRUPO_CLIENTE: TStringField;
    cds_cliCODINCLUCANC: TIntegerField;
    cds_cliEXIST_COBERT: TStringField;
    cds_cliEXISTCOPART: TStringField;
    cds_cliDATAREINC: TDateField;
    cds_cliGERAAVISO: TStringField;
    cds_cliGERAENV: TStringField;
    cds_cliGERABOL: TStringField;
    cds_cliEMVIAGEM: TStringField;
    cds_cliDTAALTERA: TDateField;
    cds_cliSERIELETRA: TStringField;
    cds_cliSERIE: TStringField;
    cds_cliRA: TStringField;
    cds_cliCURSO: TStringField;
    cds_cliIP: TStringField;
    cds_cliN_CONTRATO: TStringField;
    cds_cliMAC: TStringField;
    cds_cliMARCA: TStringField;
    cds_cliBANDA_UPLOAD: TStringField;
    cds_cliBANDA_DOWLOAD: TStringField;
    cds_cliTORRE_CONECCAO: TStringField;
    cds_cliCOD_FAIXA: TIntegerField;
    cds_cliDESCONTO: TFloatField;
    cds_cliMENSALIDADE: TFloatField;
    cds_cliPAI: TStringField;
    cds_cliLOCALTRABALUNO: TStringField;
    cds_cliDIVERSO1: TStringField;
    cds_cliDIVERSO2: TStringField;
    cds_cliTELTRABALUNO: TStringField;
    cds_cliDATA_MATRICULA: TSQLTimeStampField;
    cds_cliSITUACAOESCOLAR: TStringField;
    cds_cliCOD_TRANPORTADORA: TIntegerField;
    cds_cliCODRESPONSAVEL: TIntegerField;
    cds_cliCFOP: TStringField;
    dbcbbCARGOFUNCAO: TDBComboBox;
    lbl1: TLabel;
    dsDtsrc_e: TDataSource;
    cds_CliEnd: TClientDataSet;
    cds_CliEndLOGRADOURO: TStringField;
    cds_CliEndNUMERO: TStringField;
    cds_CliEndBAIRRO: TStringField;
    cds_CliEndCIDADE: TStringField;
    cds_CliEndUF: TStringField;
    cds_CliEndCODENDERECO: TIntegerField;
    cds_CliEndCODCLIENTE: TIntegerField;
    cds_CliEndCOMPLEMENTO: TStringField;
    cds_CliEndCEP: TStringField;
    cds_CliEndTELEFONE: TStringField;
    cds_CliEndTELEFONE1: TStringField;
    cds_CliEndTELEFONE2: TStringField;
    cds_CliEndFAX: TStringField;
    cds_CliEndE_MAIL: TStringField;
    cds_CliEndRAMAL: TStringField;
    cds_CliEndTIPOEND: TSmallintField;
    cds_CliEndDADOSADICIONAIS: TStringField;
    cds_CliEndDDD: TStringField;
    cds_CliEndDDD1: TStringField;
    cds_CliEndDDD2: TStringField;
    cds_CliEndDDD3: TStringField;
    cds_CliEndCD_IBGE: TStringField;
    cds_CliEndPAIS: TStringField;
    dsp_CliEnd: TDataSetProvider;
    sds_CliEnd: TSQLDataSet;
    sds_CliEndLOGRADOURO: TStringField;
    sds_CliEndNUMERO: TStringField;
    sds_CliEndBAIRRO: TStringField;
    sds_CliEndCIDADE: TStringField;
    sds_CliEndUF: TStringField;
    sds_CliEndCODENDERECO: TIntegerField;
    sds_CliEndCODCLIENTE: TIntegerField;
    sds_CliEndCOMPLEMENTO: TStringField;
    sds_CliEndCEP: TStringField;
    sds_CliEndTELEFONE: TStringField;
    sds_CliEndTELEFONE1: TStringField;
    sds_CliEndTELEFONE2: TStringField;
    sds_CliEndFAX: TStringField;
    sds_CliEndE_MAIL: TStringField;
    sds_CliEndRAMAL: TStringField;
    sds_CliEndTIPOEND: TSmallintField;
    sds_CliEndDADOSADICIONAIS: TStringField;
    sds_CliEndDDD: TStringField;
    sds_CliEndDDD1: TStringField;
    sds_CliEndDDD2: TStringField;
    sds_CliEndDDD3: TStringField;
    sds_CliEndCD_IBGE: TStringField;
    sds_CliEndPAIS: TStringField;
    grp3: TGroupBox;
    lbl3: TLabel;
    lbl4: TLabel;
    lbl5: TLabel;
    lbl6: TLabel;
    lbl7: TLabel;
    lbl8: TLabel;
    lbl9: TLabel;
    lbl10: TLabel;
    lbl11: TLabel;
    lbl12: TLabel;
    lbl13: TLabel;
    lbl14: TLabel;
    btn1: TBitBtn;
    dbedtLOGRADOURO: TDBEdit;
    dbedtNUMERO: TDBEdit;
    dbedtBAIRRO: TDBEdit;
    dbedtCOMPLEMENTO: TDBEdit;
    dbedtCIDADE: TDBEdit;
    dbedtUF: TDBEdit;
    dbedtCEP: TDBEdit;
    dbedtCD_IBGE: TDBEdit;
    dbedtDDD: TDBEdit;
    dbedtTELEFONE: TDBEdit;
    dbedtE_MAIL: TDBEdit;
    dbedtDDD1: TDBEdit;
    dbedtTELEFONE1: TDBEdit;
    dbedtDDD2: TDBEdit;
    dbedtTELEFONE2: TDBEdit;
    chk1: TCheckBox;
    chk2: TCheckBox;
    JvDBCalcEdit3: TJvDBCalcEdit;
    lbl15: TLabel;
    JvDBCalcEdit1: TJvDBCalcEdit;
    lbl16: TLabel;
    chk3: TCheckBox;
    sds_cliCOD_CLI: TStringField;
    sds_cliBLOQUEADO: TStringField;
    grpNome: TGroupBox;
    lblNome: TLabel;
    lblRazao: TLabel;
    dbedtRAZAOSOCIAL: TDBEdit;
    dbedtNOMECLIENTE: TDBEdit;
    dbedtRAZAOSOCIAL1: TDBEdit;
    rgTipo: TRadioGroup;
    cds_cliCOD_CLI: TStringField;
    cds_cliBLOQUEADO: TStringField;
    sds_cliCORTESIA: TStringField;
    sds_cliVALOR_CONSUMO: TFloatField;
    sds_cliVALOR_CORTESIA: TFloatField;
    sds_cliE_FORNECEDOR: TStringField;
    sds_cliCODFORNECEDOR: TIntegerField;
    sds_cliCARGOFUNCAO: TStringField;
    cds_cliCORTESIA: TStringField;
    cds_cliVALOR_CONSUMO: TFloatField;
    cds_cliVALOR_CORTESIA: TFloatField;
    cds_cliE_FORNECEDOR: TStringField;
    cds_cliCODFORNECEDOR: TIntegerField;
    cds_cliCARGOFUNCAO: TStringField;
    rgSitCad: TRadioGroup;
    lbl17: TLabel;
    dbedtRG1: TDBEdit;
    procedure FormCreate(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  fCadClientes2: TfCadClientes2;

implementation

uses UDm;

{$R *.dfm}

procedure TfCadClientes2.FormCreate(Sender: TObject);
begin
//  inherited;

end;

end.
