unit uSincronizar;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, StdCtrls, Buttons, FMTBcd, DB, DBClient, Provider, SqlExpr,
  TFlatGaugeUnit;

type
  TfSincronizar = class(TForm)
    BitBtn1: TBitBtn;
    FlatGauge1: TFlatGauge;
    BitBtn2: TBitBtn;
    sClienteCODCLIENTE: TIntegerField;
    sClienteNOMECLIENTE: TStringField;
    sClienteRAZAOSOCIAL: TStringField;
    sClienteCONTATO: TStringField;
    sClienteTIPOFIRMA: TSmallintField;
    sClienteCPF: TStringField;
    sClienteCNPJ: TStringField;
    sClienteINSCESTADUAL: TStringField;
    sClienteRG: TStringField;
    sClienteSEGMENTO: TSmallintField;
    sClienteREGIAO: TSmallintField;
    sClienteLIMITECREDITO: TFloatField;
    sClienteDATACADASTRO: TDateField;
    sClienteCODUSUARIO: TIntegerField;
    sClienteSTATUS: TSmallintField;
    sClienteHOMEPAGE: TStringField;
    sClientePRAZORECEBIMENTO: TSmallintField;
    sClientePRAZOENTREGA: TSmallintField;
    sClienteCODBANCO: TSmallintField;
    sClienteBASE_ICMS: TSmallintField;
    sClienteDATANASC: TDateField;
    sClienteCONTA_CLIENTE: TStringField;
    sClienteOBS: TStringField;
    sClienteTEM_IE: TStringField;
    sClienteDATARESC: TDateField;
    sClienteNOMEMAE: TStringField;
    sClienteSEXO: TStringField;
    sClienteFORMA_CORRESPOND: TStringField;
    sClienteGRUPO_CLIENTE: TStringField;
    sClienteCODINCLUCANC: TIntegerField;
    sClienteEXIST_COBERT: TStringField;
    sClienteEXISTCOPART: TStringField;
    sClienteDATAREINC: TDateField;
    sClienteGERAAVISO: TStringField;
    sClienteGERAENV: TStringField;
    sClienteGERABOL: TStringField;
    sClienteEMVIAGEM: TStringField;
    sClienteDTAALTERA: TDateField;
    sClienteSERIELETRA: TStringField;
    sClienteSERIE: TStringField;
    sClienteRA: TStringField;
    sClienteCURSO: TStringField;
    sClienteIP: TStringField;
    sClienteN_CONTRATO: TStringField;
    sClienteMAC: TStringField;
    sClienteMARCA: TStringField;
    sClienteBANDA_UPLOAD: TStringField;
    sClienteBANDA_DOWLOAD: TStringField;
    sClienteTORRE_CONECCAO: TStringField;
    sClienteCOD_FAIXA: TIntegerField;
    sClienteDESCONTO: TFloatField;
    sClienteMENSALIDADE: TFloatField;
    sClienteANUIDADE: TFloatField;
    sClientePARCELA: TIntegerField;
    sClientePARCELAGERADAS: TIntegerField;
    sClienteNUMERO: TIntegerField;
    sClienteDATANASCIMENTO: TSQLTimeStampField;
    sClienteANOLETIVO: TStringField;
    sClienteSITUACAOESCOLAR: TStringField;
    sClienteRGMAE: TStringField;
    sClienteCPFMAE: TStringField;
    sClientePAI: TStringField;
    sClienteRGPAI: TStringField;
    sClienteCPFPAI: TStringField;
    sClienteLANCADOCLASSE: TIntegerField;
    sClienteTRANSPORTE: TStringField;
    sClienteCIDADENASC: TStringField;
    sClienteUFNASC: TStringField;
    sClienteNACIONALIDADE: TStringField;
    sClienteCERTIDAONASCNUM: TStringField;
    sClienteLIVRONASC: TStringField;
    sClienteFLLIVRONASC: TStringField;
    sClienteLOCALTRABPAI: TStringField;
    sClienteLOCALTRABMAE: TStringField;
    sClienteTELTRABPAI: TStringField;
    sClienteTELTRABMAE: TStringField;
    sClienteINFONECESSARIAS: TStringField;
    sClienteCARTEIRAVACINACAO: TStringField;
    sClienteRAPRODESP: TStringField;
    sClienteLOCALTRABALUNO: TStringField;
    sClienteTELTRABALUNO: TStringField;
    sClienteRAPROD: TStringField;
    sClienteCERT_NAS_COMARCA: TStringField;
    sClienteCERT_NAS_UF: TStringField;
    sClienteCERT_NAS_MUNICIPIO: TStringField;
    sClienteCERT_NAS_DISTRITO: TStringField;
    sClienteCERT_NAS_SUBDISTRITO: TStringField;
    sClienteDIVERSO1: TStringField;
    sClienteDIVERSO2: TStringField;
    sClienteDATAEMISSAORG: TDateField;
    sClienteESTADORG: TStringField;
    sClienteCOMUNICAALUNO: TStringField;
    sClienteFONEMAE: TStringField;
    sClienteCELULARMAE: TStringField;
    sClienteCOMUNICAMAE: TStringField;
    sClienteFONEPAI: TStringField;
    sClienteCELULARPAI: TStringField;
    sClienteCOMUNICAPAI: TStringField;
    sClienteVALOR_MATRICULA: TFloatField;
    sClienteDATATRANSF: TDateField;
    sClienteCOR_RACA: TStringField;
    sClientePERIODO: TStringField;
    sClienteFOTO: TStringField;
    sClienteDATA_MATRICULA: TSQLTimeStampField;
    sClienteCODRESPONSAVEL: TIntegerField;
    sClienteID_COB: TIntegerField;
    sClienteCOD_TRANPORTADORA: TIntegerField;
    sClienteBLOQUEIO: TStringField;
    sClienteCFOP: TStringField;
    sClienteCOD_CLI: TStringField;
    sClienteCORTESIA: TStringField;
    sClienteVALOR_CONSUMO: TFloatField;
    sClienteVALOR_CORTESIA: TFloatField;
    sClienteE_FORNECEDOR: TStringField;
    sClienteCODFORNECEDOR: TIntegerField;
    sClienteCODFISCAL: TStringField;
    sClienteCARGOFUNCAO: TIntegerField;
    sClienteSUFRAMA: TStringField;
    sProdudoCODPRODUTO: TIntegerField;
    sProdudoFAMILIA: TStringField;
    sProdudoCATEGORIA: TStringField;
    sProdudoMARCA: TStringField;
    sProdudoUNIDADEMEDIDA: TStringField;
    sProdudoDATAULTIMACOMPRA: TDateField;
    sProdudoESTOQUEMAXIMO: TFloatField;
    sProdudoESTOQUEATUAL: TFloatField;
    sProdudoESTOQUEREPOSICAO: TFloatField;
    sProdudoESTOQUEMINIMO: TFloatField;
    sProdudoVALORUNITARIOATUAL: TFloatField;
    sProdudoVALORUNITARIOANTERIOR: TFloatField;
    sProdudoICMS: TFloatField;
    sProdudoCODALMOXARIFADO: TIntegerField;
    sProdudoIPI: TFloatField;
    sProdudoCLASSIFIC_FISCAL: TStringField;
    sProdudoCST: TStringField;
    sProdudoBASE_ICMS: TFloatField;
    sProdudoPRODUTO: TStringField;
    sProdudoPRECOMEDIO: TBCDField;
    sProdudoCOD_COMISSAO: TIntegerField;
    sProdudoMARGEM_LUCRO: TFloatField;
    sProdudoCOD_BARRA: TStringField;
    sProdudoVALOR_PRAZO: TFloatField;
    sProdudoTIPO: TStringField;
    sProdudoCONTA_DESPESA: TStringField;
    sProdudoCONTA_RECEITA: TStringField;
    sProdudoCONTA_ESTOQUE: TStringField;
    sProdudoRATEIO: TStringField;
    sProdudoCODPRO: TStringField;
    sProdudoQTDE_PCT: TFloatField;
    sProdudoPESO_QTDE: TFloatField;
    sProdudoDATACADASTRO: TSQLTimeStampField;
    sProdudoMARGEM: TFloatField;
    sProdudoPRO_COD: TStringField;
    sProdudoDATAGRAV: TDateField;
    sProdudoCODFORN: TStringField;
    sProdudoFOTOPRODUTO: TStringField;
    sProdudoLOTES: TStringField;
    sProdudoUSA: TStringField;
    sProdudoLOCALIZACAO: TStringField;
    sProdudoTIPOPRECOVENDA: TStringField;
    sProdudoVALORMINIMO: TFloatField;
    sProdudoGERADESCONTO: TStringField;
    sProdudoIMPRIMIR: TStringField;
    sProdudoVALORCOMISSAO: TFloatField;
    sProdudoORIGEM: TIntegerField;
    sProdudoNCM: TStringField;
    sProdudoIMPRESSORA_1: TStringField;
    sProdudoIMPRESSORA_2: TStringField;
    sProdudoIMPRESSORA_3: TStringField;
    sProdudoQTD: TIntegerField;
    sProdudoTAM_LOTE: TIntegerField;
    sProdudoOBS: TStringField;
    cProdutosCODPRODUTO: TIntegerField;
    cProdutosFAMILIA: TStringField;
    cProdutosCATEGORIA: TStringField;
    cProdutosMARCA: TStringField;
    cProdutosUNIDADEMEDIDA: TStringField;
    cProdutosDATAULTIMACOMPRA: TDateField;
    cProdutosESTOQUEMAXIMO: TFloatField;
    cProdutosESTOQUEATUAL: TFloatField;
    cProdutosESTOQUEREPOSICAO: TFloatField;
    cProdutosESTOQUEMINIMO: TFloatField;
    cProdutosVALORUNITARIOATUAL: TFloatField;
    cProdutosVALORUNITARIOANTERIOR: TFloatField;
    cProdutosICMS: TFloatField;
    cProdutosCODALMOXARIFADO: TIntegerField;
    cProdutosIPI: TFloatField;
    cProdutosCLASSIFIC_FISCAL: TStringField;
    cProdutosCST: TStringField;
    cProdutosBASE_ICMS: TFloatField;
    cProdutosPRODUTO: TStringField;
    cProdutosPRECOMEDIO: TBCDField;
    cProdutosCOD_COMISSAO: TIntegerField;
    cProdutosMARGEM_LUCRO: TFloatField;
    cProdutosCOD_BARRA: TStringField;
    cProdutosVALOR_PRAZO: TFloatField;
    cProdutosTIPO: TStringField;
    cProdutosCONTA_DESPESA: TStringField;
    cProdutosCONTA_RECEITA: TStringField;
    cProdutosCONTA_ESTOQUE: TStringField;
    cProdutosRATEIO: TStringField;
    cProdutosCODPRO: TStringField;
    cProdutosQTDE_PCT: TFloatField;
    cProdutosPESO_QTDE: TFloatField;
    cProdutosDATACADASTRO: TSQLTimeStampField;
    cProdutosMARGEM: TFloatField;
    cProdutosPRO_COD: TStringField;
    cProdutosDATAGRAV: TDateField;
    cProdutosCODFORN: TStringField;
    cProdutosFOTOPRODUTO: TStringField;
    cProdutosLOTES: TStringField;
    cProdutosUSA: TStringField;
    cProdutosLOCALIZACAO: TStringField;
    cProdutosTIPOPRECOVENDA: TStringField;
    cProdutosVALORMINIMO: TFloatField;
    cProdutosGERADESCONTO: TStringField;
    cProdutosIMPRIMIR: TStringField;
    cProdutosVALORCOMISSAO: TFloatField;
    cProdutosORIGEM: TIntegerField;
    cProdutosNCM: TStringField;
    cProdutosIMPRESSORA_1: TStringField;
    cProdutosIMPRESSORA_2: TStringField;
    cProdutosIMPRESSORA_3: TStringField;
    cProdutosQTD: TIntegerField;
    cProdutosTAM_LOTE: TIntegerField;
    cProdutosOBS: TStringField;
    cClienteCODCLIENTE: TIntegerField;
    cClienteNOMECLIENTE: TStringField;
    cClienteRAZAOSOCIAL: TStringField;
    cClienteCONTATO: TStringField;
    cClienteTIPOFIRMA: TSmallintField;
    cClienteCPF: TStringField;
    cClienteCNPJ: TStringField;
    cClienteINSCESTADUAL: TStringField;
    cClienteRG: TStringField;
    cClienteSEGMENTO: TSmallintField;
    cClienteREGIAO: TSmallintField;
    cClienteLIMITECREDITO: TFloatField;
    cClienteDATACADASTRO: TDateField;
    cClienteCODUSUARIO: TIntegerField;
    cClienteSTATUS: TSmallintField;
    cClienteHOMEPAGE: TStringField;
    cClientePRAZORECEBIMENTO: TSmallintField;
    cClientePRAZOENTREGA: TSmallintField;
    cClienteCODBANCO: TSmallintField;
    cClienteBASE_ICMS: TSmallintField;
    cClienteDATANASC: TDateField;
    cClienteCONTA_CLIENTE: TStringField;
    cClienteOBS: TStringField;
    cClienteTEM_IE: TStringField;
    cClienteDATARESC: TDateField;
    cClienteNOMEMAE: TStringField;
    cClienteSEXO: TStringField;
    cClienteFORMA_CORRESPOND: TStringField;
    cClienteGRUPO_CLIENTE: TStringField;
    cClienteCODINCLUCANC: TIntegerField;
    cClienteEXIST_COBERT: TStringField;
    cClienteEXISTCOPART: TStringField;
    cClienteDATAREINC: TDateField;
    cClienteGERAAVISO: TStringField;
    cClienteGERAENV: TStringField;
    cClienteGERABOL: TStringField;
    cClienteEMVIAGEM: TStringField;
    cClienteDTAALTERA: TDateField;
    cClienteSERIELETRA: TStringField;
    cClienteSERIE: TStringField;
    cClienteRA: TStringField;
    cClienteCURSO: TStringField;
    cClienteIP: TStringField;
    cClienteN_CONTRATO: TStringField;
    cClienteMAC: TStringField;
    cClienteMARCA: TStringField;
    cClienteBANDA_UPLOAD: TStringField;
    cClienteBANDA_DOWLOAD: TStringField;
    cClienteTORRE_CONECCAO: TStringField;
    cClienteCOD_FAIXA: TIntegerField;
    cClienteDESCONTO: TFloatField;
    cClienteMENSALIDADE: TFloatField;
    cClienteANUIDADE: TFloatField;
    cClientePARCELA: TIntegerField;
    cClientePARCELAGERADAS: TIntegerField;
    cClienteNUMERO: TIntegerField;
    cClienteDATANASCIMENTO: TSQLTimeStampField;
    cClienteANOLETIVO: TStringField;
    cClienteSITUACAOESCOLAR: TStringField;
    cClienteRGMAE: TStringField;
    cClienteCPFMAE: TStringField;
    cClientePAI: TStringField;
    cClienteRGPAI: TStringField;
    cClienteCPFPAI: TStringField;
    cClienteLANCADOCLASSE: TIntegerField;
    cClienteTRANSPORTE: TStringField;
    cClienteCIDADENASC: TStringField;
    cClienteUFNASC: TStringField;
    cClienteNACIONALIDADE: TStringField;
    cClienteCERTIDAONASCNUM: TStringField;
    cClienteLIVRONASC: TStringField;
    cClienteFLLIVRONASC: TStringField;
    cClienteLOCALTRABPAI: TStringField;
    cClienteLOCALTRABMAE: TStringField;
    cClienteTELTRABPAI: TStringField;
    cClienteTELTRABMAE: TStringField;
    cClienteINFONECESSARIAS: TStringField;
    cClienteCARTEIRAVACINACAO: TStringField;
    cClienteRAPRODESP: TStringField;
    cClienteLOCALTRABALUNO: TStringField;
    cClienteTELTRABALUNO: TStringField;
    cClienteRAPROD: TStringField;
    cClienteCERT_NAS_COMARCA: TStringField;
    cClienteCERT_NAS_UF: TStringField;
    cClienteCERT_NAS_MUNICIPIO: TStringField;
    cClienteCERT_NAS_DISTRITO: TStringField;
    cClienteCERT_NAS_SUBDISTRITO: TStringField;
    cClienteDIVERSO1: TStringField;
    cClienteDIVERSO2: TStringField;
    cClienteDATAEMISSAORG: TDateField;
    cClienteESTADORG: TStringField;
    cClienteCOMUNICAALUNO: TStringField;
    cClienteFONEMAE: TStringField;
    cClienteCELULARMAE: TStringField;
    cClienteCOMUNICAMAE: TStringField;
    cClienteFONEPAI: TStringField;
    cClienteCELULARPAI: TStringField;
    cClienteCOMUNICAPAI: TStringField;
    cClienteVALOR_MATRICULA: TFloatField;
    cClienteDATATRANSF: TDateField;
    cClienteCOR_RACA: TStringField;
    cClientePERIODO: TStringField;
    cClienteFOTO: TStringField;
    cClienteDATA_MATRICULA: TSQLTimeStampField;
    cClienteCODRESPONSAVEL: TIntegerField;
    cClienteID_COB: TIntegerField;
    cClienteCOD_TRANPORTADORA: TIntegerField;
    cClienteBLOQUEIO: TStringField;
    cClienteCFOP: TStringField;
    cClienteCOD_CLI: TStringField;
    cClienteCORTESIA: TStringField;
    cClienteVALOR_CONSUMO: TFloatField;
    cClienteVALOR_CORTESIA: TFloatField;
    cClienteE_FORNECEDOR: TStringField;
    cClienteCODFORNECEDOR: TIntegerField;
    cClienteCODFISCAL: TStringField;
    cClienteCARGOFUNCAO: TIntegerField;
    cClienteSUFRAMA: TStringField;
    seProdutosCODPRODUTO: TIntegerField;
    seProdutosFAMILIA: TStringField;
    seProdutosCATEGORIA: TStringField;
    seProdutosMARCA: TStringField;
    seProdutosUNIDADEMEDIDA: TStringField;
    seProdutosDATAULTIMACOMPRA: TDateField;
    seProdutosESTOQUEMAXIMO: TFloatField;
    seProdutosESTOQUEATUAL: TFloatField;
    seProdutosESTOQUEREPOSICAO: TFloatField;
    seProdutosESTOQUEMINIMO: TFloatField;
    seProdutosVALORUNITARIOATUAL: TFloatField;
    seProdutosVALORUNITARIOANTERIOR: TFloatField;
    seProdutosICMS: TFloatField;
    seProdutosCODALMOXARIFADO: TIntegerField;
    seProdutosIPI: TFloatField;
    seProdutosCLASSIFIC_FISCAL: TStringField;
    seProdutosCST: TStringField;
    seProdutosBASE_ICMS: TFloatField;
    seProdutosPRODUTO: TStringField;
    seProdutosPRECOMEDIO: TBCDField;
    seProdutosCOD_COMISSAO: TIntegerField;
    seProdutosMARGEM_LUCRO: TFloatField;
    seProdutosCOD_BARRA: TStringField;
    seProdutosVALOR_PRAZO: TFloatField;
    seProdutosTIPO: TStringField;
    seProdutosCONTA_DESPESA: TStringField;
    seProdutosCONTA_RECEITA: TStringField;
    seProdutosCONTA_ESTOQUE: TStringField;
    seProdutosRATEIO: TStringField;
    seProdutosCODPRO: TStringField;
    seProdutosQTDE_PCT: TFloatField;
    seProdutosPESO_QTDE: TFloatField;
    seProdutosDATACADASTRO: TSQLTimeStampField;
    seProdutosMARGEM: TFloatField;
    seProdutosPRO_COD: TStringField;
    seProdutosDATAGRAV: TDateField;
    seProdutosCODFORN: TStringField;
    seProdutosFOTOPRODUTO: TStringField;
    seProdutosLOTES: TStringField;
    seProdutosUSA: TStringField;
    seProdutosLOCALIZACAO: TStringField;
    seProdutosTIPOPRECOVENDA: TStringField;
    seProdutosVALORMINOMO: TFloatField;
    seProdutosVALORMINIMO: TFloatField;
    seProdutosVALORCOMISSAO: TFloatField;
    seProdutosGERADESCONTO: TStringField;
    seProdutosIMPRIMIR: TStringField;
    seProdutosORIGEM: TIntegerField;
    seProdutosNCM: TStringField;
    seProdutosIMPRESSORA_1: TStringField;
    seProdutosIMPRESSORA_2: TStringField;
    seProdutosIMPRESSORA_3: TStringField;
    seProdutosQTD: TIntegerField;
    seProdutosTAM_LOTE: TIntegerField;
    seProdutosOBS: TStringField;
    ceProdutosCODPRODUTO: TIntegerField;
    ceProdutosFAMILIA: TStringField;
    ceProdutosCATEGORIA: TStringField;
    ceProdutosMARCA: TStringField;
    ceProdutosUNIDADEMEDIDA: TStringField;
    ceProdutosDATAULTIMACOMPRA: TDateField;
    ceProdutosESTOQUEMAXIMO: TFloatField;
    ceProdutosESTOQUEATUAL: TFloatField;
    ceProdutosESTOQUEREPOSICAO: TFloatField;
    ceProdutosESTOQUEMINIMO: TFloatField;
    ceProdutosVALORUNITARIOATUAL: TFloatField;
    ceProdutosVALORUNITARIOANTERIOR: TFloatField;
    ceProdutosICMS: TFloatField;
    ceProdutosCODALMOXARIFADO: TIntegerField;
    ceProdutosIPI: TFloatField;
    ceProdutosCLASSIFIC_FISCAL: TStringField;
    ceProdutosCST: TStringField;
    ceProdutosBASE_ICMS: TFloatField;
    ceProdutosPRODUTO: TStringField;
    ceProdutosPRECOMEDIO: TBCDField;
    seClienteCODCLIENTE: TIntegerField;
    seClienteNOMECLIENTE: TStringField;
    seClienteRAZAOSOCIAL: TStringField;
    seClienteCONTATO: TStringField;
    seClienteTIPOFIRMA: TSmallintField;
    seClienteCPF: TStringField;
    seClienteCNPJ: TStringField;
    seClienteINSCESTADUAL: TStringField;
    seClienteRG: TStringField;
    seClienteSEGMENTO: TSmallintField;
    seClienteREGIAO: TSmallintField;
    seClienteLIMITECREDITO: TFloatField;
    seClienteDATACADASTRO: TDateField;
    seClienteCODUSUARIO: TIntegerField;
    seClienteSTATUS: TSmallintField;
    seClienteHOMEPAGE: TStringField;
    seClientePRAZORECEBIMENTO: TSmallintField;
    seClientePRAZOENTREGA: TSmallintField;
    seClienteCODBANCO: TSmallintField;
    seClienteBASE_ICMS: TSmallintField;
    seClienteDATANASC: TDateField;
    seClienteCONTA_CLIENTE: TStringField;
    seClienteOBS: TStringField;
    seClienteTEM_IE: TStringField;
    seClienteDATARESC: TDateField;
    seClienteNOMEMAE: TStringField;
    seClienteSEXO: TStringField;
    seClienteFORMA_CORRESPOND: TStringField;
    seClienteGRUPO_CLIENTE: TStringField;
    seClienteCODINCLUCANC: TIntegerField;
    seClienteEXIST_COBERT: TStringField;
    seClienteEXISTCOPART: TStringField;
    seClienteDATAREINC: TDateField;
    seClienteGERAAVISO: TStringField;
    seClienteGERAENV: TStringField;
    seClienteGERABOL: TStringField;
    seClienteEMVIAGEM: TStringField;
    seClienteDTAALTERA: TDateField;
    seClienteSERIELETRA: TStringField;
    seClienteSERIE: TStringField;
    seClienteRA: TStringField;
    seClienteCURSO: TStringField;
    seClienteIP: TStringField;
    seClienteN_CONTRATO: TStringField;
    seClienteMAC: TStringField;
    seClienteMARCA: TStringField;
    seClienteBANDA_UPLOAD: TStringField;
    seClienteBANDA_DOWLOAD: TStringField;
    seClienteTORRE_CONECCAO: TStringField;
    seClienteCOD_FAIXA: TIntegerField;
    seClienteDESCONTO: TFloatField;
    seClienteMENSALIDADE: TFloatField;
    seClienteANUIDADE: TFloatField;
    seClientePARCELA: TIntegerField;
    seClientePARCELAGERADAS: TIntegerField;
    seClienteNUMERO: TIntegerField;
    seClienteDATANASCIMENTO: TSQLTimeStampField;
    seClienteANOLETIVO: TStringField;
    seClienteSITUACAOESCOLAR: TStringField;
    seClienteRGMAE: TStringField;
    seClienteCPFMAE: TStringField;
    seClientePAI: TStringField;
    seClienteRGPAI: TStringField;
    seClienteCPFPAI: TStringField;
    seClienteLANCADOCLASSE: TIntegerField;
    seClienteTRANSPORTE: TStringField;
    seClienteCIDADENASC: TStringField;
    seClienteUFNASC: TStringField;
    seClienteNACIONALIDADE: TStringField;
    seClienteCERTIDAONASCNUM: TStringField;
    seClienteLIVRONASC: TStringField;
    seClienteFLLIVRONASC: TStringField;
    seClienteLOCALTRABPAI: TStringField;
    seClienteLOCALTRABMAE: TStringField;
    seClienteTELTRABPAI: TStringField;
    seClienteTELTRABMAE: TStringField;
    seClienteINFONECESSARIAS: TStringField;
    seClienteCARTEIRAVACINACAO: TStringField;
    seClienteRAPRODESP: TStringField;
    seClienteLOCALTRABALUNO: TStringField;
    seClienteTELTRABALUNO: TStringField;
    seClienteRAPROD: TStringField;
    seClienteCERT_NAS_COMARCA: TStringField;
    seClienteCERT_NAS_UF: TStringField;
    seClienteCERT_NAS_MUNICIPIO: TStringField;
    seClienteCERT_NAS_DISTRITO: TStringField;
    seClienteCERT_NAS_SUBDISTRITO: TStringField;
    seClienteDIVERSO1: TStringField;
    seClienteDIVERSO2: TStringField;
    seClienteDATAEMISSAORG: TDateField;
    seClienteESTADORG: TStringField;
    seClienteCOMUNICAALUNO: TStringField;
    seClienteFONEMAE: TStringField;
    seClienteCELULARMAE: TStringField;
    seClienteCOMUNICAMAE: TStringField;
    seClienteFONEPAI: TStringField;
    seClienteCELULARPAI: TStringField;
    seClienteCOMUNICAPAI: TStringField;
    seClienteVALOR_MATRICULA: TFloatField;
    seClienteDATATRANSF: TDateField;
    seClienteCOR_RACA: TStringField;
    seClientePERIODO: TStringField;
    seClienteFOTO: TStringField;
    seClienteDATA_MATRICULA: TSQLTimeStampField;
    seClienteCODRESPONSAVEL: TIntegerField;
    seClienteID_COB: TIntegerField;
    seClienteCOD_TRANPORTADORA: TIntegerField;
    seClienteBLOQUEADO: TStringField;
    seClienteBLOQUEIO: TStringField;
    seClienteCFOP: TStringField;
    seClienteCOD_CLI: TStringField;
    seClienteCODFISCAL: TStringField;
    seClienteCORTESIA: TStringField;
    seClienteVALOR_CONSUMO: TFloatField;
    seClienteVALOR_CORTESIA: TFloatField;
    seClienteE_FORNECEDOR: TStringField;
    seClienteCODFORNECEDOR: TIntegerField;
    seClienteCARGOFUNCAO: TIntegerField;
    seClienteSUFRAMA: TStringField;
    ceClienteCODCLIENTE: TIntegerField;
    ceClienteNOMECLIENTE: TStringField;
    ceClienteRAZAOSOCIAL: TStringField;
    ceClienteCONTATO: TStringField;
    ceClienteTIPOFIRMA: TSmallintField;
    ceClienteCPF: TStringField;
    ceClienteCNPJ: TStringField;
    ceClienteINSCESTADUAL: TStringField;
    ceClienteRG: TStringField;
    ceClienteSEGMENTO: TSmallintField;
    ceClienteREGIAO: TSmallintField;
    ceClienteLIMITECREDITO: TFloatField;
    ceClienteDATACADASTRO: TDateField;
    ceClienteCODUSUARIO: TIntegerField;
    ceClienteSTATUS: TSmallintField;
    ceClienteHOMEPAGE: TStringField;
    ceClientePRAZORECEBIMENTO: TSmallintField;
    ceClientePRAZOENTREGA: TSmallintField;
    ceClienteCODBANCO: TSmallintField;
    ceClienteBASE_ICMS: TSmallintField;
    ceClienteDATANASC: TDateField;
    ceClienteCONTA_CLIENTE: TStringField;
    ceClienteOBS: TStringField;
    ceClienteTEM_IE: TStringField;
    ceClienteDATARESC: TDateField;
    ceClienteNOMEMAE: TStringField;
    ceClienteSEXO: TStringField;
    ceClienteFORMA_CORRESPOND: TStringField;
    ceClienteGRUPO_CLIENTE: TStringField;
    ceClienteCODINCLUCANC: TIntegerField;
    ceClienteEXIST_COBERT: TStringField;
    ceClienteEXISTCOPART: TStringField;
    ceClienteDATAREINC: TDateField;
    ceClienteGERAAVISO: TStringField;
    ceClienteGERAENV: TStringField;
    ceClienteGERABOL: TStringField;
    ceClienteEMVIAGEM: TStringField;
    ceClienteDTAALTERA: TDateField;
    ceClienteSERIELETRA: TStringField;
    ceClienteSERIE: TStringField;
    ceClienteRA: TStringField;
    ceClienteCURSO: TStringField;
    ceClienteIP: TStringField;
    ceClienteN_CONTRATO: TStringField;
    ceClienteMAC: TStringField;
    ceClienteMARCA: TStringField;
    ceClienteBANDA_UPLOAD: TStringField;
    ceClienteBANDA_DOWLOAD: TStringField;
    ceClienteTORRE_CONECCAO: TStringField;
    ceClienteCOD_FAIXA: TIntegerField;
    ceClienteDESCONTO: TFloatField;
    ceClienteMENSALIDADE: TFloatField;
    ceClienteANUIDADE: TFloatField;
    ceClientePARCELA: TIntegerField;
    ceClientePARCELAGERADAS: TIntegerField;
    ceClienteNUMERO: TIntegerField;
    ceClienteDATANASCIMENTO: TSQLTimeStampField;
    ceClienteANOLETIVO: TStringField;
    ceClienteSITUACAOESCOLAR: TStringField;
    ceClienteRGMAE: TStringField;
    ceClienteCPFMAE: TStringField;
    ceClientePAI: TStringField;
    ceClienteRGPAI: TStringField;
    ceClienteCPFPAI: TStringField;
    ceClienteLANCADOCLASSE: TIntegerField;
    ceClienteTRANSPORTE: TStringField;
    ceClienteCIDADENASC: TStringField;
    ceClienteUFNASC: TStringField;
    ceClienteNACIONALIDADE: TStringField;
    ceClienteCERTIDAONASCNUM: TStringField;
    ceClienteLIVRONASC: TStringField;
    ceClienteFLLIVRONASC: TStringField;
    ceClienteLOCALTRABPAI: TStringField;
    ceClienteLOCALTRABMAE: TStringField;
    ceClienteTELTRABPAI: TStringField;
    ceClienteTELTRABMAE: TStringField;
    ceClienteINFONECESSARIAS: TStringField;
    ceClienteCARTEIRAVACINACAO: TStringField;
    ceClienteRAPRODESP: TStringField;
    ceClienteLOCALTRABALUNO: TStringField;
    ceClienteTELTRABALUNO: TStringField;
    ceClienteRAPROD: TStringField;
    ceClienteCERT_NAS_COMARCA: TStringField;
    ceClienteCERT_NAS_UF: TStringField;
    ceClienteCERT_NAS_MUNICIPIO: TStringField;
    ceClienteCERT_NAS_DISTRITO: TStringField;
    ceClienteCERT_NAS_SUBDISTRITO: TStringField;
    ceClienteDIVERSO1: TStringField;
    ceClienteDIVERSO2: TStringField;
    ceClienteDATAEMISSAORG: TDateField;
    ceClienteESTADORG: TStringField;
    ceClienteCOMUNICAALUNO: TStringField;
    ceClienteFONEMAE: TStringField;
    ceClienteCELULARMAE: TStringField;
    ceClienteCOMUNICAMAE: TStringField;
    ceClienteFONEPAI: TStringField;
    ceClienteCELULARPAI: TStringField;
    ceClienteCOMUNICAPAI: TStringField;
    ceClienteVALOR_MATRICULA: TFloatField;
    ceClienteDATATRANSF: TDateField;
    ceClienteCOR_RACA: TStringField;
    ceClientePERIODO: TStringField;
    ceClienteFOTO: TStringField;
    ceClienteDATA_MATRICULA: TSQLTimeStampField;
    ceClienteCODRESPONSAVEL: TIntegerField;
    ceClienteID_COB: TIntegerField;
    ceClienteCOD_TRANPORTADORA: TIntegerField;
    ceClienteBLOQUEADO: TStringField;
    ceClienteBLOQUEIO: TStringField;
    ceClienteCFOP: TStringField;
    ceClienteCOD_CLI: TStringField;
    ceClienteCODFISCAL: TStringField;
    ceClienteCORTESIA: TStringField;
    ceClienteVALOR_CONSUMO: TFloatField;
    ceClienteVALOR_CORTESIA: TFloatField;
    ceClienteE_FORNECEDOR: TStringField;
    ceClienteCODFORNECEDOR: TIntegerField;
    ceClienteCARGOFUNCAO: TIntegerField;
    ceClienteSUFRAMA: TStringField;
    ceProdutosCOD_COMISSAO: TIntegerField;
    ceProdutosMARGEM_LUCRO: TFloatField;
    ceProdutosCOD_BARRA: TStringField;
    ceProdutosVALOR_PRAZO: TFloatField;
    ceProdutosTIPO: TStringField;
    ceProdutosCONTA_DESPESA: TStringField;
    ceProdutosCONTA_RECEITA: TStringField;
    ceProdutosCONTA_ESTOQUE: TStringField;
    ceProdutosRATEIO: TStringField;
    ceProdutosCODPRO: TStringField;
    ceProdutosQTDE_PCT: TFloatField;
    ceProdutosPESO_QTDE: TFloatField;
    ceProdutosDATACADASTRO: TSQLTimeStampField;
    ceProdutosMARGEM: TFloatField;
    ceProdutosPRO_COD: TStringField;
    ceProdutosDATAGRAV: TDateField;
    ceProdutosCODFORN: TStringField;
    ceProdutosFOTOPRODUTO: TStringField;
    ceProdutosLOTES: TStringField;
    ceProdutosUSA: TStringField;
    ceProdutosLOCALIZACAO: TStringField;
    ceProdutosTIPOPRECOVENDA: TStringField;
    ceProdutosVALORMINOMO: TFloatField;
    ceProdutosVALORMINIMO: TFloatField;
    ceProdutosVALORCOMISSAO: TFloatField;
    ceProdutosGERADESCONTO: TStringField;
    ceProdutosIMPRIMIR: TStringField;
    ceProdutosORIGEM: TIntegerField;
    ceProdutosNCM: TStringField;
    ceProdutosIMPRESSORA_1: TStringField;
    ceProdutosIMPRESSORA_2: TStringField;
    ceProdutosIMPRESSORA_3: TStringField;
    ceProdutosQTD: TIntegerField;
    ceProdutosTAM_LOTE: TIntegerField;
    ceProdutosOBS: TStringField;
    procedure BitBtn1Click(Sender: TObject);
    procedure BitBtn2Click(Sender: TObject);

  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  fSincronizar: TfSincronizar;

implementation

uses UDm;

{$R *.dfm}

procedure TfSincronizar.BitBtn1Click(Sender: TObject);
var
  vari: integer;
begin
    // Copio dados tabela de PRODUTOS
  Try
    cProdutos.Open;
    FlatGauge1.Progress := 0;
    FlatGauge1.MaxValue := cProdutos.RecordCount;
    cProdutos.First;
    while not cProdutos.Eof do
    begin
      ceProdutos.Close;
      ceProdutos.Params[0].AsInteger := cProdutosCODPRODUTO.AsInteger;
      ceProdutos.Open;
      if (ceProdutos.IsEmpty) then
      begin
        ceProdutos.append;
        for vari := 0 to cProdutos.fieldcount -1 do
        begin
          if (cProdutos.fields[vari].fieldkind = fkdata) then
            ceProdutos.fields[vari].value := cProdutos.fieldbyname(cProdutos.fields[vari].fieldname).value;
        end;
        ceProdutos.ApplyUpdates(0);
      end
      else
      begin
        if (ceProdutosVALOR_PRAZO.Value <> cProdutosVALOR_PRAZO.Value) then
        begin
          ceProdutos.Edit;
          ceProdutosCODPRO.Value := cProdutosCODPRO.Value;
          ceProdutosPRODUTO.AsString := cProdutosPRODUTO.AsString;
          ceProdutosVALOR_PRAZO.Value := cProdutosVALOR_PRAZO.Value;
          ceProdutos.ApplyUpdates(0);
        end;  
      end;
      cProdutos.Next;
      FlatGauge1.Progress := FlatGauge1.Progress + 1;
    end;
    MessageDlg('Produtos exportados com suscesso', mtWarning, [mbOK], 0);
    cProdutos.Close;
    ceProdutos.Close;
  Except
    MessageDlg('Erro ao exportar Produtos', mtWarning, [mbOK], 0);
  end;

end;

procedure TfSincronizar.BitBtn2Click(Sender: TObject);
var
  vari: integer;
begin
    // Copio dados tabela de CLIENTES
  Try
    cCliente.Open;
    FlatGauge1.Progress := 0;
    FlatGauge1.MaxValue := cCliente.RecordCount;
    cCliente.First;
    while not cCliente.Eof do
    begin
      ceCliente.Close;
      ceCliente.Params[0].AsInteger := cClienteCODCLIENTE.AsInteger;
      ceCliente.Open;
      if (ceCliente.IsEmpty) then
      begin
        ceCliente.append;
        for vari := 0 to cCliente.fieldcount -1 do
        begin
          if (cCliente.fields[vari].fieldkind = fkdata) then
            ceCliente.fields[vari].value := cCliente.fieldbyname(cCliente.fields[vari].fieldname).value;
        end;
        ceCliente.ApplyUpdates(0);
      end
      else
      begin
         if ((ceClienteNOMECLIENTE.AsString <> cClienteNOMECLIENTE.AsString)
           or (ceClienteRAZAOSOCIAL.AsString <> cClienteRAZAOSOCIAL.AsString)
            or (ceClienteTIPOFIRMA.AsString <> cClienteTIPOFIRMA.AsString)
             or (ceClienteCNPJ.AsString <> cClienteCNPJ.AsString)
              or (ceClienteINSCESTADUAL.AsString <> cClienteINSCESTADUAL.AsString)
               or (ceClienteSTATUS.AsInteger <> cClienteSTATUS.AsInteger)
                or (ceClienteCNPJ.AsString <> cClienteCNPJ.AsString)) then
         begin
           ceCliente.Edit;
           ceClienteNOMECLIENTE.AsString := cClienteNOMECLIENTE.AsString;
           ceClienteRAZAOSOCIAL.AsString := cClienteRAZAOSOCIAL.AsString;
           ceClienteTIPOFIRMA.AsString := cClienteTIPOFIRMA.AsString;
           ceClienteCNPJ.AsString := cClienteCNPJ.AsString;
           ceClienteINSCESTADUAL.AsString := cClienteINSCESTADUAL.AsString;
           ceClienteSTATUS.AsInteger := cClienteSTATUS.AsInteger;
           ceClienteCNPJ.AsString := cClienteCNPJ.AsString;
           ceCliente.ApplyUpdates(0);
         end;
      end;
      cCliente.Next;
      FlatGauge1.Progress := FlatGauge1.Progress + 1;
    end;
    MessageDlg('Clientes exportados com suscesso', mtWarning, [mbOK], 0);
    cCliente.Close;
    ceCliente.Close;
  Except
    MessageDlg('Erro ao exportar Clientes', mtWarning, [mbOK], 0);
  end;
end;

end.
