CREATE TRIGGER CORRIGE_VALOR_FATURA FOR RECEBIMENTO ACTIVE
BEFORE UPDATE POSITION 0
AS 
BEGIN 
    if (old.VALOR_RESTO_SST is null) then
        new.VALOR_RESTO_SST = old.VALOR_RESTO;
    if (new.VALST >= 0) then
        new.VALOR_RESTO = (new.VALST + new.VALOR_RESTO_SST);
END