CREATE OR ALTER TRIGGER PROIBE_ALT_DEL_NF FOR NOTAFISCAL ACTIVE
BEFORE UPDATE OR DELETE POSITION 0
as 
BEGIN 
  if ((old.PROTOCOLOENV is not null) or (old.PROTOCOLOCANC is not null)) then
    exception ALTERA_NFE;	
END