CREATE TABLE OS_DET
(
  ID_OS_DET INTEGER NOT NULL,
  ID_OS INTEGER NOT NULL,
  DESCRICAO_SERV VARCHAR(300),
  STATUS CHAR(1),
  CODUSUARIO INTEGER,
  PRECO VALORES DEFAULT 0.00,
  QTDE VALORES DEFAULT 0.00,
  SERV_EXECUTADO TEXTO300,
  CONSTRAINT INTEG_426 PRIMARY KEY (ID_OS_DET)
);

ALTER TABLE OS_DET ADD CONSTRAINT FK_OS_DET_OS
  FOREIGN KEY (ID_OS) REFERENCES OS (CODOS) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE OS_DET ADD CONSTRAINT FK_OS_DET_USUARIO
  FOREIGN KEY (CODUSUARIO) REFERENCES FUNCIONARIO (COD_FUNCIONARIO) ON UPDATE NO ACTION ON DELETE NO ACTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON OS_DET TO  SYSDBA WITH GRANT OPTION;




