DROP TABLE OS; 

CREATE TABLE OS
(
  CODOS INTEGER NOT NULL,
  CODCLIENTE INTEGER NOT NULL,
  CODVEICULO INTEGER,
  CODMOVIMENTO INTEGER,
  DATAMOVIMENTO DATE,
  DATA_SISTEMA TIMESTAMP,
  STATUS CHAR(1),
  DATA_INI DATE,
  DATA_FIM DATE,
  CODUSUARIO INTEGER,
  CONSTRAINT INTEG_206 PRIMARY KEY (CODOS)
);

ALTER TABLE OS ADD CONSTRAINT FK_OS_CLIENTE
  FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTES (CODCLIENTE) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE OS ADD CONSTRAINT FK_OS_USUARIO
  FOREIGN KEY (CODUSUARIO) REFERENCES FUNCIONARIO (COD_FUNCIONARIO) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE OS ADD CONSTRAINT FK_OS_VEICULO
  FOREIGN KEY (CODVEICULO) REFERENCES VEICULO (COD_VEICULO) ON UPDATE NO ACTION ON DELETE NO ACTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON OS TO  SYSDBA WITH GRANT OPTION;

