set term ^;

CREATE OR ALTER PROCEDURE PROGRAMACAORECEBIMENTO(
  DATAINI DATE,
  DATAFIM DATE)
RETURNS(
  NOTAF VARCHAR(18) CHARACTER SET WIN1252,
  CLIENTE VARCHAR(50) CHARACTER SET WIN1252,
  EMISSAO DATE,
  VALORNF DOUBLE PRECISION,
  VENCIMENTO DATE,
  TOTALGERAL DOUBLE PRECISION,
  DATAREC DATE,
  DATAFINAL DATE)
AS
BEGIN
  /* Procedure body */
  DATAFINAL = dataini - 1;
  while (:DATAFINAL <= :DATAFIM) do
  begin
    DATAFINAL = udf_IncDay(:DATAFINAL, 7);
    DATAREC = udf_IncDay(:DATAFINAL, 2);
    For select rc.TITULO, rc.EMISSAO, rc.DATAVENCIMENTO, rc.VALOR_RESTO, cl.RAZAOSOCIAL
      from RECEBIMENTO rc inner join CLIENTES cl on cl.CODCLIENTE = rc.CODCLIENTE
        where rc.DATAVENCIMENTO BETWEEN :DATAINI and :DATAFINAL order by rc.DATAVENCIMENTO
    into :NOTAF, :EMISSAO, :VENCIMENTO , :VALORNF, :CLIENTE do
    begin
    
       SUSPEND;
    end
  end
END;
