CREATE TABLE OS_DET
(
  ID_OS_DET INTEGER NOT NULL,
  ID_OS INTEGER NOT NULL,
  CODPRODUTO INTEGER NOT NULL,
  DESCRICAO_SERV VARCHAR(1024),
  RESPONSAVEL VARCHAR(150),
  STATUS CHAR(1),
  TIPO CHAR(1), -- comment 'P-PRODUTO ou S-SERVICO' 
  QTDE VALOR, 
  PRECO VALOR, 
  DESCONTO VALOR,
  DESCPERCENT COMPUTED BY ((DESCONTO/PRECO)*100),
  VALORTOTAL  COMPUTED BY ((PRECO-DESCONTO)*QTDE),
  ID_OSDET_SERV INTEGER, -- Codigo da OS DET. SERVICO 
  CONSTRAINT INTEG_404 PRIMARY KEY (ID_OS_DET)
);
