CREATE TABLE OS_DET
(
  ID_OS_DET INTEGER NOT NULL,
  ID_OS INTEGER NOT NULL,
  DESCRICAO_SERV VARCHAR(1024),
  RESPONSAVEL VARCHAR(150),
  STATUS CHAR(1),
  CONSTRAINT INTEG_404 PRIMARY KEY (ID_OS_DET)
);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON OS_DET TO  SYSDBA WITH GRANT OPTION;

