CREATE TABLE ESTOQUEMES
(
  CODPRODUTO INTEGER NOT NULL,
  LOTE VARCHAR(60) NOT NULL,
  MESANO DATE NOT NULL,
  QTDEENTRADA DOUBLE PRECISION,
  QTDECOMPRA DOUBLE PRECISION,
  QTDEDEVCOMPRA DOUBLE PRECISION,
  QTDESAIDA DOUBLE PRECISION,
  QTDEVENDA DOUBLE PRECISION,
  QTDEPERDA DOUBLE PRECISION,
  PRECOCUSTO DOUBLE PRECISION,
  PRECOCOMPRA DOUBLE PRECISION,
  PRECOVENDA DOUBLE PRECISION,
  CENTROCUSTO INTEGER NOT NULL,
  QTDEDEVVENDA DOUBLE PRECISION,
  SALDOMESANTERIOR DOUBLE PRECISION,
  CONSTRAINT INTEG_408 PRIMARY KEY (CODPRODUTO,LOTE,MESANO,CENTROCUSTO)
);

ALTER TABLE ESTOQUEMES ADD SALDOESTOQUE COMPUTED BY (SALDOMESANTERIOR + 
  QTDEENTRADA + QTDECOMPRA + QTDEDEVCOMPRA - QTDEVENDA - QTDESAIDA - QTDEPERDA -  QTDEDEVVENDA);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ESTOQUEMES TO  SYSDBA WITH GRANT OPTION;

